### PR TITLE
update Observability stack

### PR DESCRIPTION
**Pull request by altokarev**

### CODE REVIEW

**Review by voborgus — APPROVED** [review]

**Comment by alem355** [comment]
Привет, давай обсудим на ежеквартальном апдейте стека. Let's talk about it on the annual tech stack update meeting.

**Comment by altokarev** [comment]
> Привет, давай обсудим на ежеквартальном апдейте стека. Let's talk about it on the annual tech stack update meeting.

PagerDuty research has been already started anyway. And Gogomonia deployment has been ordered to Flant too.

**Comment by altokarev** [comment]
@alem355 👋

**Comment by voborgus** [comment]
@alem355 @altokarev any news here so far? :)

**Comment by alem355** [comment]
Peter has provided all updatets on the last tech meeting. I will update the stack on Friday 22 04

**Comment by altokarev** [comment]
@alem355 @voborgus ау!

**Pull request closed without merging**
